import anthropic
import openai
import requests
import streamlit as st
from bs4 import BeautifulSoup
from openai import OpenAI

st.title("🔗 HW2 - URL Summarizer")
st.write(
    "Enter a web page URL and get a summary generated by an LLM. "
    "Choose the summary type, output language, and the LLM from the sidebar."
)

SUMMARY_INSTRUCTIONS = {
    "100 words": "Summarize the page in about 100 words.",
    "2 connecting paragraphs": "Summarize the page in 2 connecting paragraphs.",
    "5 bullet points": "Summarize the page in 5 bullet points.",
}

LANGUAGES = ["English", "Hindi", "Spanish", "French"]

# Each LLM has a cheap default model and a set of 'advanced' models.
LLMS = {
    "OpenAI": {
        "secret": "OPENAI_API_KEY",
        "default_model": "gpt-5-nano",
        "advanced_models": ["gpt-4.1", "gpt-5-chat-latest"],
    },
    "Anthropic (Claude)": {
        "secret": "ANTHROPIC_API_KEY",
        "default_model": "claude-haiku-4-5",
        "advanced_models": ["claude-opus-5", "claude-sonnet-5"],
    },
}


def read_url_content(url):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for HTTP errors
        soup = BeautifulSoup(response.content, "html.parser")
        return soup.get_text()
    except requests.RequestException as e:
        print(f"Error reading {url}: {e}")
        return None


def get_api_key(secret_name):
    try:
        return st.secrets[secret_name]
    except (KeyError, FileNotFoundError):
        # No secrets.toml at all, or the key is missing from it.
        return None


@st.cache_resource(show_spinner=False)
def get_openai_client(api_key):
    client = OpenAI(api_key=api_key)
    client.models.list()  # Fails if the key is not valid for OpenAI.
    return client


@st.cache_resource(show_spinner=False)
def get_anthropic_client(api_key):
    client = anthropic.Anthropic(api_key=api_key)
    client.models.list()  # Fails if the key is not valid for Anthropic.
    return client


with st.sidebar:
    st.header("Summary options")
    language = st.selectbox("Output language", LANGUAGES)
    summary_type = st.selectbox("Summary type", list(SUMMARY_INSTRUCTIONS.keys()))

    st.header("LLM options")
    llm_name = st.selectbox("LLM", list(LLMS.keys()))
    llm = LLMS[llm_name]
    use_advanced_model = st.checkbox("Use advanced model")
    if use_advanced_model:
        model = st.selectbox("Choose a model", llm["advanced_models"])
    else:
        model = llm["default_model"]
    st.caption(f"Using `{model}`")

url = st.text_input("Web page URL", placeholder="https://example.com")

if url:
    api_key = get_api_key(llm["secret"])
    if not api_key:
        st.error(f"Add `{llm['secret']}` to your secrets to use {llm_name}.")
        st.stop()

    try:
        if llm_name == "OpenAI":
            client = get_openai_client(api_key)
        else:
            client = get_anthropic_client(api_key)
    except (openai.OpenAIError, anthropic.APIError) as error:
        st.error(f"The {llm_name} API key is not valid: {error}")
        st.stop()

    document = read_url_content(url)

    if not document:
        st.error("Could not read that URL. Check the address and try again.")
    else:
        messages = [
            {
                "role": "user",
                "content": (
                    f"Here's the content of a web page: {document} \n\n---\n\n "
                    f"{SUMMARY_INSTRUCTIONS[summary_type]} "
                    f"Write the summary in {language}."
                ),
            }
        ]

        try:
            if llm_name == "OpenAI":
                stream = client.chat.completions.create(
                    model=model,
                    messages=messages,
                    stream=True,
                )
                st.write_stream(stream)
            else:
                with client.messages.stream(
                    model=model,
                    max_tokens=2000,
                    messages=messages,
                ) as stream:
                    st.write_stream(stream.text_stream)
        except (openai.OpenAIError, anthropic.APIError) as error:
            st.error(f"{llm_name} could not generate a summary: {error}")
else:
    st.info("Please enter a URL to generate a summary.")
